#!/bin/bash
for n in {01..28}
do
	dir=tests/test$n
	[ -d $dir ] || continue
        input=$dir/input
	co_output=$dir/output
	my_output=$(mktemp)
	python3 -i IntelligenceArtificial1.py < $input > $my_output 2> /dev/null
        echo -n "$n: "
        if diff $co_output $my_output > /dev/null
	then
		echo 'PASSED!'
	else
		echo 'Failed.'
		echo -n 'Mine: '
		cat $my_output
		echo -n 'Correct: '
		cat $co_output
	fi
	echo
done
